version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - "./db_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: wordpress

  wordpress:
    depends_on:
      - mysql
    image: wordpress:4.3.1-apache
    ports:
      - "8000:80"
    volumes:
      - "./wordpress/:/var/www/html/"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: passwd